name: Trigger auto deployment for pemenagetestprivateendpoint

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/pemenagetestprivateendpoint-AutoDeployTrigger-eda368e6-bdd7-41b3-b996-d81760f13c26.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PEMENAGETESTPRIVATEENDPOINT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PEMENAGETESTPRIVATEENDPOINT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PEMENAGETESTPRIVATEENDPOINT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.PEMENAGETESTPRIVATEENDPOINT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PEMENAGETESTPRIVATEENDPOINT_REGISTRY_PASSWORD }}
          containerAppName: pemenagetestprivateendpoint
          resourceGroup: privateEndpointRG
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


